### ISSUE TITLE
Is it possible to add a "deploy section" in README?

### ISSUE THREAD

**Issue by CipherWang** [nervosnetwork/ckb-production-scripts#2]
I find it's difficult to figure out suitable tooling to deploy a script. It would be great if there is a tutorial or something like that to tell others how to deploy & use it.

**Comment by XuJiandong** [comment]
https://github.com/nervosnetwork/ckb-cli/pull/397
A subcommand 'deploy' is added in this PR.

https://github.com/nervosnetwork/ckb-cli/wiki/Deploy-contracts
