### ISSUE TITLE
[Question] Auth library Status

### ISSUE THREAD

**Issue by phroi** [nervosnetwork/ckb-production-scripts#71]
Reading [Nervos Blog post on CKB VM V1 Upgrade](https://www.nervos.org/blog/major-protocol-upgrade-diving-into-ckb-vm-v1), in the section **Exec Syscall** Auth library #37 is pointed at as a good example of `exec` syscall application.

[The markdown doc linked in the auth library PR reads](https://github.com/XuJiandong/docs-bank/blob/master/auth.md#high-level-apis):
> **High Level APIs**
> The following API can combine the low level APIs together:
> 
> `int ckb_auth(EntryType* entry, CkbAuthType *id, uint8_t *signature, uint32_t signature_size, const uint8_t *message32)`
> Most of developers only need to use this function without knowing the low level APIs.

So my questions are:
**1)** Is this API stable? Can I safely base iCKB scripts on it?
**2)** Is it already deployed on main-net? If so, what's the Auth library cell address?

Keep up the great work :muscle:
Phroi

**Comment by XuJiandong** [comment]
1) stable
2) not on mainnet, deployed on testnet

**Comment by phroi** [comment]
Good to know, thanks!!
